### PR TITLE
Update

### LINKED ISSUE #24: PyPI 0.7.1 sdist doesnt include LICENSE

### PR DESCRIPTION
**Pull request by frenzymadness**
of packaging and testing matrix. Resolves #24

### CODE REVIEW

**Comment by hroncok** [comment]
3.10:

> AttributeError: module 'test.support' has no attribute 'skip_unless_symlink'

**Comment by frenzymadness** [comment]
@torsava @encukou anybody interested in a review here? It should be easy.

**Review by encukou — APPROVED** [review]
Looks good!
Tests run and pass. Differences in the resulting wheel look minor & sane.

**Comment by frenzymadness** [comment]
Thank you!

**Pull request merged**
