### PR TITLE
Fix a bug in Python 3.4 pyc/pyo files handling

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: https://github.com/frenzymadness/compileall2/issues/4

### CODE REVIEW

**Comment by frenzymadness** [comment]
@hroncok

**Comment by hroncok** [comment]
Still not sure 3.4 support is worth it.

**Comment by frenzymadness** [comment]
If this change fixes only one problem we have with 3.4, then why not keep the support.

**Comment by hroncok** [comment]
We can revisit 3.4 support later.

**Pull request merged**
